{
  "openapi": "3.0.1",
  "info": {
    "title": "个人项目",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "宠物"
    }
  ],
  "paths": {
    "/pet/{petId}": {
      "get": {
        "summary": "查询宠物详情",
        "deprecated": false,
        "description": "",
        "tags": [
          "宠物"
        ],
        "parameters": [
          {
            "name": "petId",
            "in": "path",
            "description": "宠物 ID",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "minimum": 0,
                      "maximum": 0,
                      "description": "状态码"
                    },
                    "data": {
                      "$ref": "#/components/schemas/Pet",
                      "description": "宠物信息"
                    }
                  },
                  "required": [
                    "code",
                    "data"
                  ],
                  "x-apifox-orders": [
                    "code",
                    "data"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "example": {
                  "code": 0,
                  "data": {
                    "name": "Hello Kity",
                    "photoUrls": [
                      "http://dummyimage.com/400x400"
                    ],
                    "id": 3,
                    "category": {
                      "id": 71,
                      "name": "Cat"
                    },
                    "tags": [
                      {
                        "id": 22,
                        "name": "Cat"
                      }
                    ],
                    "status": "sold"
                  }
                }
              }
            },
            "headers": {},
            "x-apifox-name": "成功"
          },
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "code",
                    "message"
                  ],
                  "x-apifox-orders": [
                    "code",
                    "message"
                  ]
                }
              }
            },
            "headers": {},
            "x-apifox-name": "参数不正确"
          },
          "404": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "code",
                    "message"
                  ],
                  "x-apifox-orders": [
                    "code",
                    "message"
                  ]
                }
              }
            },
            "headers": {},
            "x-apifox-name": "记录不存在"
          }
        },
        "security": [],
        "x-apifox-folder": "示例项目",
        "x-apifox-status": "released",
        "x-run-in-apifox": "https://app.apifox.com/web/project/6159270/apis/api-280289167-run"
      },
      "delete": {
        "summary": "删除宠物信息",
        "deprecated": false,
        "description": "",
        "tags": [
          "宠物"
        ],
        "parameters": [
          {
            "name": "petId",
            "in": "path",
            "description": "Pet id to delete",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "api_key",
            "in": "header",
            "description": "",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "minimum": 0,
                      "maximum": 0
                    }
                  },
                  "required": [
                    "code"
                  ],
                  "x-apifox-orders": [
                    "code"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "example": {
                  "code": 0
                }
              }
            },
            "headers": {},
            "x-apifox-name": "成功"
          }
        },
        "security": [],
        "x-apifox-folder": "示例项目",
        "x-apifox-status": "released",
        "x-run-in-apifox": "https://app.apifox.com/web/project/6159270/apis/api-280289170-run"
      }
    },
    "/pet": {
      "post": {
        "summary": "新建宠物信息",
        "deprecated": false,
        "description": "",
        "tags": [
          "宠物"
        ],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "description": "宠物名",
                    "example": "Hello Kitty",
                    "type": "string"
                  },
                  "status": {
                    "description": "宠物销售状态",
                    "example": "sold",
                    "type": "string"
                  }
                },
                "required": [
                  "name",
                  "status"
                ]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "minimum": 0,
                      "maximum": 0
                    },
                    "data": {
                      "$ref": "#/components/schemas/Pet",
                      "description": "宠物信息"
                    }
                  },
                  "required": [
                    "code",
                    "data"
                  ],
                  "x-apifox-orders": [
                    "code",
                    "data"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "example": {
                  "code": 0,
                  "data": {
                    "name": "Hello Kity",
                    "photoUrls": [
                      "http://dummyimage.com/400x400"
                    ],
                    "id": 3,
                    "category": {
                      "id": 71,
                      "name": "Cat"
                    },
                    "tags": [
                      {
                        "id": 22,
                        "name": "Cat"
                      }
                    ],
                    "status": "sold"
                  }
                }
              }
            },
            "headers": {},
            "x-apifox-name": "成功"
          }
        },
        "security": [],
        "x-apifox-folder": "示例项目",
        "x-apifox-status": "released",
        "x-run-in-apifox": "https://app.apifox.com/web/project/6159270/apis/api-280289168-run"
      },
      "put": {
        "summary": "修改宠物信息",
        "deprecated": false,
        "description": "",
        "tags": [
          "宠物"
        ],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "data": {
                      "$ref": "#/components/schemas/Pet",
                      "description": "宠物信息"
                    }
                  },
                  "required": [
                    "code",
                    "data"
                  ],
                  "x-apifox-orders": [
                    "code",
                    "data"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "example": {
                  "code": 0,
                  "data": {
                    "name": "Hello Kity",
                    "photoUrls": [
                      "http://dummyimage.com/400x400"
                    ],
                    "id": 3,
                    "category": {
                      "id": 71,
                      "name": "Cat"
                    },
                    "tags": [
                      {
                        "id": 22,
                        "name": "Cat"
                      }
                    ],
                    "status": "sold"
                  }
                }
              }
            },
            "headers": {},
            "x-apifox-name": "成功"
          },
          "404": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {},
                  "x-apifox-orders": [],
                  "x-apifox-ignore-properties": []
                }
              }
            },
            "headers": {},
            "x-apifox-name": "记录不存在"
          },
          "405": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {},
                  "x-apifox-orders": [],
                  "x-apifox-ignore-properties": []
                }
              }
            },
            "headers": {},
            "x-apifox-name": "验证错误"
          }
        },
        "security": [],
        "x-apifox-folder": "示例项目",
        "x-apifox-status": "released",
        "x-run-in-apifox": "https://app.apifox.com/web/project/6159270/apis/api-280289169-run"
      }
    },
    "/pet/findByStatus": {
      "get": {
        "summary": "根据状态查找宠物列表",
        "deprecated": false,
        "description": "",
        "tags": [
          "宠物"
        ],
        "parameters": [
          {
            "name": "status",
            "in": "query",
            "description": "Status values that need to be considered for filter",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Pet",
                    "description": "宠物信息"
                  }
                },
                "example": {
                  "code": 0,
                  "data": [
                    {
                      "name": "Hello Kity",
                      "photoUrls": [
                        "http://dummyimage.com/400x400"
                      ],
                      "id": 3,
                      "category": {
                        "id": 71,
                        "name": "Cat"
                      },
                      "tags": [
                        {
                          "id": 22,
                          "name": "Cat"
                        }
                      ],
                      "status": "sold"
                    },
                    {
                      "name": "White Dog",
                      "photoUrls": [
                        "http://dummyimage.com/400x400"
                      ],
                      "id": 3,
                      "category": {
                        "id": 71,
                        "name": "Dog"
                      },
                      "tags": [
                        {
                          "id": 22,
                          "name": "Dog"
                        }
                      ],
                      "status": "sold"
                    }
                  ]
                }
              }
            },
            "headers": {},
            "x-apifox-name": "成功"
          },
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    }
                  },
                  "required": [
                    "code"
                  ],
                  "x-apifox-orders": [
                    "code"
                  ],
                  "x-apifox-ignore-properties": []
                }
              }
            },
            "headers": {},
            "x-apifox-name": "错误的 status 值"
          }
        },
        "security": [],
        "x-apifox-folder": "示例项目",
        "x-apifox-status": "released",
        "x-run-in-apifox": "https://app.apifox.com/web/project/6159270/apis/api-280289171-run"
      }
    },
    "/user/list": {
      "get": {
        "summary": "名称为userlist",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer",
                      "description": "ID 编号",
                      "x-apifox-mock": "1"
                    },
                    "name": {
                      "type": "string",
                      "x-apifox-mock": "zhao",
                      "description": "名称"
                    },
                    "phone": {
                      "type": "string",
                      "x-apifox-mock": "130111111"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "d": {
                          "type": "string",
                          "x-apifox-mock": "1"
                        }
                      },
                      "x-apifox-orders": [
                        "d"
                      ],
                      "required": [
                        "d"
                      ],
                      "x-apifox-ignore-properties": []
                    }
                  },
                  "x-apifox-orders": [
                    "id",
                    "name",
                    "phone",
                    "data"
                  ],
                  "required": [
                    "name",
                    "phone",
                    "data"
                  ],
                  "x-apifox-ignore-properties": []
                }
              }
            },
            "headers": {},
            "x-apifox-name": "成功"
          }
        },
        "security": [],
        "x-apifox-folder": "示例项目",
        "x-apifox-status": "developing",
        "x-run-in-apifox": "https://app.apifox.com/web/project/6159270/apis/api-280290489-run"
      }
    },
    "/add_user": {
      "post": {
        "summary": "添加用户",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "name",
            "in": "query",
            "description": "",
            "required": false,
            "example": "allenq",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "phone",
            "in": "query",
            "description": "",
            "required": false,
            "example": "13222222",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "email",
            "in": "query",
            "description": "",
            "required": false,
            "example": "ewq@23.com",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "password",
            "in": "query",
            "description": "",
            "required": false,
            "example": "12345",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "x-apifox-mock": "成功"
                    }
                  },
                  "x-apifox-orders": [
                    "message"
                  ],
                  "required": [
                    "message"
                  ],
                  "x-apifox-ignore-properties": []
                }
              }
            },
            "headers": {},
            "x-apifox-name": "成功"
          }
        },
        "security": [],
        "x-apifox-folder": "",
        "x-apifox-status": "developing",
        "x-run-in-apifox": "https://app.apifox.com/web/project/6159270/apis/api-280290714-run"
      }
    }
  },
  "components": {
    "schemas": {
      "Pet": {
        "required": [
          "name",
          "photoUrls",
          "id",
          "category",
          "tags",
          "status"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "minimum": 1,
            "description": "宠物ID编号"
          },
          "category": {
            "$ref": "#/components/schemas/Category",
            "description": "分组"
          },
          "name": {
            "type": "string",
            "description": "名称",
            "examples": [
              "doggie"
            ]
          },
          "photoUrls": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "照片URL"
          },
          "tags": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Tag"
            },
            "description": "标签"
          },
          "status": {
            "type": "string",
            "description": "宠物销售状态",
            "enum": [
              "available",
              "pending",
              "sold"
            ]
          }
        },
        "x-apifox-orders": [
          "id",
          "category",
          "name",
          "photoUrls",
          "tags",
          "status"
        ],
        "x-apifox-ignore-properties": [],
        "x-apifox-folder": "示例数据模型"
      },
      "Category": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "minimum": 1,
            "description": "分组ID编号"
          },
          "name": {
            "type": "string",
            "description": "分组名称"
          }
        },
        "xml": {
          "name": "Category"
        },
        "x-apifox-orders": [
          "id",
          "name"
        ],
        "x-apifox-ignore-properties": [],
        "x-apifox-folder": "示例数据模型"
      },
      "Tag": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "minimum": 1,
            "description": "标签ID编号"
          },
          "name": {
            "type": "string",
            "description": "标签名称"
          }
        },
        "xml": {
          "name": "Tag"
        },
        "x-apifox-orders": [
          "id",
          "name"
        ],
        "x-apifox-ignore-properties": [],
        "x-apifox-folder": "示例数据模型"
      }
    },
    "securitySchemes": {}
  },
  "servers": [],
  "security": []
}